kafka:
  bootstrap_servers: "kafka:9092"
  topic_raw: "cdr_raw"
  topic_flat: "cdr_flattened"
  topic_error: "cdr_error"
  security_protocol: "PLAINTEXT"

tuning:
  linger_ms: 5
  batch_bytes: 32768
  compression: "lz4"
  retries: 10
  enable_idempotence: true
  max_in_flight: 5

logging:
  config_path: "/opt/app/config/logging.json"
